name: Dependency Review

on:
  push:
    branches: [ first ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Dependency Review
        uses: github/dependency-review-action@v2
        with:
          output-format: json
          output-file: dependency-review.json

      - name: Upload Dependency Review artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-review
          path: dependency-review.json
