name: Slack Notify

on:
  workflow_call:
    inputs:
      message:
        required: false
        type: string
      artifact-name:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      message:
        required: false
        type: string
      artifact-name:
        required: false
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      # Download artifact if specified
      - name: Download artifact
        if: ${{ inputs.artifact-name }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: artifact_content

      # Prepare message
      - name: Prepare message
        id: prepare
        shell: bash
        run: |
          if [ -n "${{ inputs.message }}" ]; then
            MSG="${{ inputs.message }}"
          elif [ -d "artifact_content" ]; then
            MSG=$(cat artifact_content/*)
            MSG="```$MSG```"
          else
            MSG="No message provided"
          fi
          # Prepare full JSON payload and escape properly
          PAYLOAD=$(python3 -c "import json; print(json.dumps({'text': '$MSG'}))")
          echo "PAYLOAD=$PAYLOAD" >> $GITHUB_ENV

      # Send to Slack using the official action
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook-type: incoming-webhook
          payload:  ${{ env.PAYLOAD }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
